# Generated by Django 4.2.14 on 2024-08-03 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('sensor_id', models.CharField(max_length=32)),
                ('value', models.CharField(max_length=2048)),
            ],
        ),
    ]
