# Generated by Django 4.2.14 on 2024-08-04 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acquisition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='sensor_id',
        ),
    ]
