# Generated by Django 4.2.14 on 2024-08-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquisition', '0002_remove_sensordata_sensor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='sensor_id',
            field=models.CharField(default='0', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='value',
            field=models.FloatField(),
        ),
    ]
